package raw

type Port struct {
	NodeGUID                            string
	PortGUID                            string
	PortNum                             string
	MKey                                string
	GIDPrfx                             string
	MSMLID                              string
	LID                                 string
	CapMsk                              string
	MKeyLeasePeriod                     string
	DiagCode                            string
	LinkWidthActv                       string
	LinkWidthSup                        string
	LinkWidthEn                         string
	LocalPortNum                        string
	LinkSpeedEn                         string
	LinkSpeedActv                       string
	LMC                                 string
	MKeyProtBits                        string
	LinkDownDefState                    string
	PortPhyState                        string
	PortState                           string
	LinkSpeedSup                        string
	VLArbHighCap                        string
	VLHighLimit                         string
	InitType                            string
	VLCap                               string
	MSMSL                               string
	NMTU                                string
	FilterRawOutb                       string
	FilterRawInb                        string
	PartEnfOutb                         string
	PartEnfInb                          string
	OpVLs                               string
	HoQLife                             string
	VLStallCnt                          string
	MTUCap                              string
	InitTypeReply                       string
	VLArbLowCap                         string
	PKeyViolations                      string
	MKeyViolations                      string
	SubnTmo                             string
	MulticastPKeyTrapSuppressionEnabled string
	ClientReregister                    string
	GUIDCap                             string
	QKeyViolations                      string
	MaxCreditHint                       string
	OverrunErrs                         string
	LocalPhyError                       string
	RespTimeValue                       string
	LinkRoundTripLatency                string
	OOOSLMask                           string
	CapMsk2                             string
	FECActv                             string
	RetransActv                         string
}
